### ISSUE TITLE
Create session store which is automatically killed on browser close

### ISSUE THREAD

**Issue by jimd33463** [gorilla/sessions#115]
How do I go about creating a session-based cookie that will go away when the browser closes?
I've tried using combinations of "NewCookieStore" vs. "NewFilesystemStore" with setting MaxAge to zero, but no luck.  Thanks, Jim

**Comment by jimd33463** [comment]
I think I found the problem in the vendor file (gorilla>session>store.go).  There is a line where the cookie is deleted if MaxAge <= 0, however it should be MaxAge < 0.  Was this fixed in a subsequent release?

**Comment by elithrar** [comment]
Yes, it was. What ref are you on? (What does git log sho)?

**Comment by jimd33463** [comment]
I’m inexperienced with GitHub.  I see there is a “pull request” for this change.  Does this mean that an edited version of the code is available for me to download?  How do I go about doing that?  If it’s too much to explain, no problem – I’ll need to learn more about how all this works.

Thanks, Jim

**Comment by elithrar** [comment]
You don't need to touch GitHub - run:

go get -u github.com/gorilla/sessions

... to update your package locally.

**Comment by kisielk** [comment]
@elithrar are you sure this was fixed? #103 is still open and that looks like the PR that would fix this.

**Comment by jimd33463** [comment]
Yeah, I don't see a branch that contains the fix.  Also, when I run the 'go get' command (elithrar) the message returned is: "You are not currently on a branch.  Please specify which branch you want to merge with."

**Comment by elithrar** [comment]
My mistake - now I remember why we didn't do implement #103 - due to the
(possibly dangerous) breaking behaviour.

There may not be an opportunity to fix this directly.

**Comment by joernlenoch** [comment]
As this is still an issue - and it took me a while to find this issue...

Please consider removing all comments that suggest that the implementation works and consider adding a warning to the core README about "session" not working.
